/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_davidzavala;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Create = new javax.swing.JDialog();
        JB_New1 = new javax.swing.JButton();
        JB_Back1 = new javax.swing.JButton();
        Exit2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JB_SaveShow = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        TF_ShowName1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JS_Puntuacion = new javax.swing.JSpinner();
        CB_Genero = new javax.swing.JComboBox<>();
        CB_Tipo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        TF_ClaudilistName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Show4List = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_AllShows = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        JB_SaveList = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Listas = new javax.swing.JDialog();
        CB_ListName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Series = new javax.swing.JList<>();
        JB_Delete = new javax.swing.JButton();
        JB_Edit = new javax.swing.JButton();
        JB_New = new javax.swing.JButton();
        JB_Back = new javax.swing.JButton();
        JB_Exit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        JB_Crear = new javax.swing.JButton();
        JB_Archivos = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        Create.setUndecorated(true);
        Create.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_New1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Video.png"))); // NOI18N
        JB_New1.setBorder(null);
        JB_New1.setBorderPainted(false);
        JB_New1.setContentAreaFilled(false);
        JB_New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_New1ActionPerformed(evt);
            }
        });
        Create.getContentPane().add(JB_New1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, 50));

        JB_Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_Back1.setBorder(null);
        JB_Back1.setBorderPainted(false);
        JB_Back1.setContentAreaFilled(false);
        JB_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back1ActionPerformed(evt);
            }
        });
        Create.getContentPane().add(JB_Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, 50));

        Exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit0.png"))); // NOI18N
        Exit2.setBorder(null);
        Exit2.setBorderPainted(false);
        Exit2.setContentAreaFilled(false);
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        Create.getContentPane().add(Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 50));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_SaveShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveShow.setBorder(null);
        JB_SaveShow.setBorderPainted(false);
        JB_SaveShow.setContentAreaFilled(false);
        JB_SaveShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveShowActionPerformed(evt);
            }
        });
        jPanel1.add(JB_SaveShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 60, 60));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Puntuacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 40));

        jFormattedTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 100, 40));

        TF_ShowName1.setBackground(new java.awt.Color(102, 102, 102));
        TF_ShowName1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        TF_ShowName1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(TF_ShowName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 40));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Año");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 30));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Tipo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 40));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Genero");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 40));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Nombre");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 40));

        JS_Puntuacion.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel1.add(JS_Puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 70, 40));

        CB_Genero.setBackground(new java.awt.Color(102, 102, 102));
        CB_Genero.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        CB_Genero.setForeground(new java.awt.Color(0, 0, 0));
        CB_Genero.setModel(new DefaultComboBoxModel()

        );
        jPanel1.add(CB_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 200, 40));

        CB_Tipo.setBackground(new java.awt.Color(102, 102, 102));
        CB_Tipo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        CB_Tipo.setForeground(new java.awt.Color(0, 0, 0));
        CB_Tipo.setModel(new DefaultComboBoxModel()

        );
        jPanel1.add(CB_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 40));

        jTabbedPane1.addTab("Serie", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF_ClaudilistName.setBackground(new java.awt.Color(102, 102, 102));
        TF_ClaudilistName.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        TF_ClaudilistName.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(TF_ClaudilistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 40));

        JL_Show4List.setBackground(new java.awt.Color(102, 102, 102));
        JL_Show4List.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JL_Show4List.setForeground(new java.awt.Color(51, 51, 51));
        JL_Show4List.setModel(new DefaultListModel()
        );
        jScrollPane2.setViewportView(JL_Show4List);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 300, 320));

        JL_AllShows.setBackground(new java.awt.Color(102, 102, 102));
        JL_AllShows.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JL_AllShows.setForeground(new java.awt.Color(51, 51, 51));
        JL_AllShows.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(JL_AllShows);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 320));

        jToggleButton1.setText("Agregar a Lista");
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 50));

        JB_SaveList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveList.setBorder(null);
        JB_SaveList.setBorderPainted(false);
        JB_SaveList.setContentAreaFilled(false);
        JB_SaveList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveListActionPerformed(evt);
            }
        });
        jPanel2.add(JB_SaveList, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 60, 60));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 90));

        jTabbedPane1.addTab("Claudilist", jPanel2);

        Create.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 850, 490));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Crear");
        Create.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 70));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/geek_gamer.png"))); // NOI18N
        Fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Create.getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        Listas.setUndecorated(true);
        Listas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_ListName.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        CB_ListName.setForeground(new java.awt.Color(204, 204, 204));
        CB_ListName.setModel(new DefaultComboBoxModel()
        );
        Listas.getContentPane().add(CB_ListName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 210, 40));

        JL_Series.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JL_Series.setForeground(new java.awt.Color(204, 204, 204));
        JL_Series.setModel(new DefaultListModel()
        );
        jScrollPane1.setViewportView(JL_Series);

        Listas.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 770, 450));

        JB_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        JB_Delete.setBorder(null);
        JB_Delete.setBorderPainted(false);
        JB_Delete.setContentAreaFilled(false);
        Listas.getContentPane().add(JB_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, 50));

        JB_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        JB_Edit.setBorder(null);
        JB_Edit.setBorderPainted(false);
        JB_Edit.setContentAreaFilled(false);
        Listas.getContentPane().add(JB_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 50));

        JB_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_New.setBorder(null);
        JB_New.setBorderPainted(false);
        JB_New.setContentAreaFilled(false);
        JB_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewActionPerformed(evt);
            }
        });
        Listas.getContentPane().add(JB_New, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 50));

        JB_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_Back.setBorder(null);
        JB_Back.setBorderPainted(false);
        JB_Back.setContentAreaFilled(false);
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });
        Listas.getContentPane().add(JB_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        JB_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit0.png"))); // NOI18N
        JB_Exit1.setBorder(null);
        JB_Exit1.setBorderPainted(false);
        JB_Exit1.setContentAreaFilled(false);
        JB_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit1ActionPerformed(evt);
            }
        });
        Listas.getContentPane().add(JB_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 50));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Claudilists");
        Listas.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 70));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/geek_gamer.png"))); // NOI18N
        Fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Listas.getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Big Add.png"))); // NOI18N
        JB_Crear.setBorder(null);
        JB_Crear.setBorderPainted(false);
        JB_Crear.setContentAreaFilled(false);
        JB_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 260));

        JB_Archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/big movie.png"))); // NOI18N
        JB_Archivos.setBorder(null);
        JB_Archivos.setBorderPainted(false);
        JB_Archivos.setContentAreaFilled(false);
        JB_Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, 270));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit0.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 50));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Nueva Lista");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 70));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Listas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, 70));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Clau List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/geek_gamer.png"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void JB_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit1ActionPerformed

    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit2ActionPerformed

    private void JB_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearActionPerformed
        Create.pack();
        Create.setLocationRelativeTo(null);
        Create.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_CrearActionPerformed

    private void JB_ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ArchivosActionPerformed
        Listas.pack();
        Listas.setLocationRelativeTo(null);
        Listas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_ArchivosActionPerformed

    private void JB_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back1ActionPerformed
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Create.setVisible(false);
    }//GEN-LAST:event_JB_Back1ActionPerformed

    private void JB_New1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_New1ActionPerformed
        Listas.pack();
        Listas.setLocationRelativeTo(null);
        Listas.setVisible(true);
        Create.setVisible(false);
    }//GEN-LAST:event_JB_New1ActionPerformed

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Listas.setVisible(false);
    }//GEN-LAST:event_JB_BackActionPerformed

    private void JB_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewActionPerformed
        Create.pack();
        Create.setLocationRelativeTo(null);
        Create.setVisible(true);
        Listas.setVisible(false);
    }//GEN-LAST:event_JB_NewActionPerformed

    private void JB_SaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SaveListActionPerformed

    private void JB_SaveShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SaveShowActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Genero;
    private javax.swing.JComboBox<String> CB_ListName;
    private javax.swing.JComboBox<String> CB_Tipo;
    private javax.swing.JDialog Create;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit2;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton JB_Archivos;
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_Back1;
    private javax.swing.JButton JB_Crear;
    private javax.swing.JButton JB_Delete;
    private javax.swing.JButton JB_Edit;
    private javax.swing.JButton JB_Exit1;
    private javax.swing.JButton JB_New;
    private javax.swing.JButton JB_New1;
    private javax.swing.JButton JB_SaveList;
    private javax.swing.JButton JB_SaveShow;
    private javax.swing.JList<String> JL_AllShows;
    private javax.swing.JList<String> JL_Series;
    private javax.swing.JList<String> JL_Show4List;
    private javax.swing.JSpinner JS_Puntuacion;
    private javax.swing.JDialog Listas;
    private javax.swing.JTextField TF_ClaudilistName;
    private javax.swing.JTextField TF_ShowName1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
